### ISSUE TITLE
Syntax warnings with 3.12.3 version of python

### ISSUE THREAD

**Issue by ljg701** [em00k/NextBuildPro#1]
Hi Em00k,

Have just set up next build pro on a new win 11 machine with latest version of python (3.12.3), am getting following syntax warnings upon compilation. Issue doesn't occur after downgrading to 3.10.2.

D:\programming\zxspectrumnext\nextbuild-pro\Scripts\nextbuild.py:153: SyntaxWarning: invalid escape sequence '\h'
  subprocess.run([EMU_DIR+'\hdfmonkey.exe','put','/CSpect/cspect-next-2gb.img','autoexec.bas','/nextzxos/autoexec.bas'])
D:\programming\zxspectrumnext\nextbuild-pro\Scripts\nextbuild.py:166: SyntaxWarning: invalid escape sequence '\h'
  subprocess.run([EMU_DIR+'\hdfmonkey.exe','put','/CSpect/cspect-next-2gb.img',loaderfile,'/'+loaderfile])
D:\programming\zxspectrumnext\nextbuild-pro\Scripts\nextbuild.py:168: SyntaxWarning: invalid escape sequence '\h'
  subprocess.run([EMU_DIR+'\hdfmonkey.exe','put','/CSpect/cspect-next-2gb.img',filenamenoext+ext,'/'+outfilenoext+ext])
D:\programming\zxspectrumnext\nextbuild-pro\Scripts\nextbuild.py:171: SyntaxWarning: invalid escape sequence '\l'
  subprocess.Popen([EMU_DIR+'\launchnextzxos.bat',head_tail[0]+'/Memory.txt',EMU_DIR])

**Comment by em00k** [comment]
Thanks. Looks like we need to change the \ to / in the scripts. I'll take a look. Thanks!

**Comment by em00k** [comment]
I've fixes the escape sequences so this solve the issue, I didn't run in to any problems here so I think is fixed :)
